// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __c_mnist_dense_8_b2iS_H__
#define __c_mnist_dense_8_b2iS_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct c_mnist_dense_8_b2iS_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 32;
  static const unsigned AddressRange = 784;
  static const unsigned AddressWidth = 10;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(c_mnist_dense_8_b2iS_ram) {
        ram[0] = "0b10111110101010110011101100111110";
        ram[1] = "0b10111111100001010000100111000010";
        ram[2] = "0b00111111010001001001110000011000";
        ram[3] = "0b00111111011010011101011111011000";
        ram[4] = "0b00111111000010100011111110101010";
        ram[5] = "0b00111111001101111000100111001111";
        ram[6] = "0b10111111001011101100100011110010";
        ram[7] = "0b00111110111111000111001110001100";
        ram[8] = "0b00111111100010100111101000011111";
        ram[9] = "0b00111111101000001001001000101000";
        for (unsigned i = 10; i < 784 ; i = i + 1) {
            ram[i] = "0b00000000000000000000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(c_mnist_dense_8_b2iS) {


static const unsigned DataWidth = 32;
static const unsigned AddressRange = 784;
static const unsigned AddressWidth = 10;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


c_mnist_dense_8_b2iS_ram* meminst;


SC_CTOR(c_mnist_dense_8_b2iS) {
meminst = new c_mnist_dense_8_b2iS_ram("c_mnist_dense_8_b2iS_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~c_mnist_dense_8_b2iS() {
    delete meminst;
}


};//endmodule
#endif
